on:
  schedules:
    - cron: 0 9 * * *
name: Nightly update
jobs:
  npmCi:
    name: nightly update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - run: npm ci
      - name: clear routes
        run: rm -rf openapi/*/operations/* cache
      - name: update GHE routes
        run: node bin/octokit-rest-routes.js update --ghe
      - name: update .com routes
        run: node bin/octokit-rest-routes.js update
      - name: config git email
        run: git config --global user.email 'octokitbot@martynus.net'
      - name: config git name
        run: git config --global user.name 'OctokitBot'
      - name: routes update pull request
        run: node bin/create-pull-request-on-change.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
