on:
  release:
    types: [published]

name: Notify users
jobs:
  notify:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: node bin/notify-users
        env:
          PRIVATE_KEY: ${{ secrets.OCTOKIT_ROUTES_APP_PRIVATE_KEY }}
          INPUT_EVENT_TYPE: octokit-routes-release
          INPUT_VERSION: ${{ github.event.release.tag_name }}
