on:
  schedule:
    # https://crontab.guru/every-hour
    - cron: 0 * * * *
  repository_dispatch:
    types: [github-docs-update]
name: Update
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - run: git checkout routes-update || true
      - run: npm ci
      - name: clear routes
        run: rm -rf openapi/*/operations/* cache
      - name: update GHE routes
        run: node bin/octokit-rest-routes.js update --ghe
      - name: update .com routes
        run: node bin/octokit-rest-routes.js update
      - name: update cache
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "ðŸ¤–ðŸ“¯ Octokit routes changed"
          body: |
            I found new changes on https://developer.github.com/v3/ and thought I'd let you know about it ðŸ‘‹ðŸ¤–

            I can't tell if the changes are fixes, features or breaking, you'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/routes/blob/master/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).
          branch: "routes-update"
          author: "Octokit Bot <octokitbot@martynus.net>"
          path: "cache/"
          commit-message: "build: cache"
      - name: update GHE routes
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "routes-update"
          author: "Octokit Bot <octokitbot@martynus.net>"
          path: "openapi/api.github.com/"
          commit-message: "WIP: api.github.com routes update"
      - name: update api.github.com routes
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "routes-update"
          author: "Octokit Bot <octokitbot@martynus.net>"
          path: "openapi/ghe*"
          commit-message: "WIP: GHE routes update"
